#!/usr/bin/env bash
#
# Regenerate wallpapers.js from the contents of wallpaper-picutes/.
#
# Run this after adding or removing images. It exists because Chrome cannot list
# a directory at runtime (chrome.runtime.getPackageDirectoryEntry was MV2-only)
# and the page lives on file://, where fetch() of a local JSON index is blocked
# by CORS. A generated classic script sidesteps both.
#
# Each entry also records whether the image is LIGHT behind the clock. In zen mode
# the scrim is removed, so a near-white wallpaper would swallow white text; the page
# flips to dark text instead of putting an overlay back. Measuring here means the
# page pays nothing at runtime -- and it could not measure this itself anyway, since
# reading pixels from a file:// image taints the canvas.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

DIR=wallpaper-picutes
[ -d "$DIR" ] || { echo "index-wallpapers.sh: no such directory: $DIR" >&2; exit 1; }

python3 - "$DIR" > wallpapers.js <<'PY'
import os, sys, json
from urllib.parse import quote

directory = sys.argv[1]
extensions = {".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"}

try:
    from PIL import Image, ImageStat
    # One of these wallpapers is 21334x12000; without this Pillow refuses it as a
    # decompression bomb. draft() keeps the decode cheap regardless.
    Image.MAX_IMAGE_PIXELS = None
except ImportError:
    Image = None
    print("// NOTE: Pillow not installed - every wallpaper assumed dark.",
          file=sys.stderr)

LIGHT_THRESHOLD = 145  # mean 0-255 luminance behind the clock

def is_light(path):
    if Image is None:
        return False
    try:
        with Image.open(path) as im:
            im.draft("L", (256, 256))   # cheap reduced-size decode for JPEG
            im = im.convert("L")
            w, h = im.size
            # Only the band the clock and dates actually sit on.
            box = (int(w * 0.2), int(h * 0.35), int(w * 0.8), int(h * 0.65))
            return ImageStat.Stat(im.crop(box)).mean[0] > LIGHT_THRESHOLD
    except Exception as err:
        print("// WARNING: could not measure %s: %s" % (path, err), file=sys.stderr)
        return False

names = sorted(
    n for n in os.listdir(directory)
    if os.path.splitext(n)[1].lower() in extensions
)

entries = []
for n in names:
    # Percent-encode the filename: some of these contain a space or an apostrophe,
    # which would otherwise break the CSS url() and the preload <img>.
    entry = {"src": directory + "/" + quote(n)}
    if is_light(os.path.join(directory, n)):
        entry["light"] = True
    entries.append(entry)

print("// Generated by tools/index-wallpapers.sh -- do not edit by hand.")
print("globalThis.SP_WALLPAPERS = " + json.dumps(entries, indent=2) + ";")

print("// %d images, %d of them light" % (
    len(entries), sum(1 for e in entries if e.get("light"))))
PY

printf 'wallpapers.js: %s\n' "$(tail -1 wallpapers.js | sed 's|// ||')"
